/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#131313',
        'on-background': '#e5e2e1',
        'surface-dim': '#131313',
        'surface': '#131313',
        'surface-bright': '#3a3939',
        'surface-variant': '#353534',
        'surface-container': '#201f1f',
        'surface-container-low': '#1c1b1b',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#e3beb8',
        'primary': '#ffb4a8',
        'on-primary': '#690000',
        'primary-container': '#8b0000',
        'on-primary-container': '#ff907f',
        'primary-fixed': '#ffdad4',
        'on-primary-fixed': '#410000',
        'primary-fixed-dim': '#ffb4a8',
        'on-primary-fixed-variant': '#920703',
        'secondary': '#fff9ef',
        'on-secondary': '#3a3000',
        'secondary-container': '#ffdb3c',
        'on-secondary-container': '#725f00',
        'secondary-fixed': '#ffe16d',
        'on-secondary-fixed': '#221b00',
        'secondary-fixed-dim': '#e9c400',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'tertiary': '#c8c6c5',
        'on-tertiary': '#303030',
        'tertiary-container': '#424242',
        'on-tertiary-container': '#b0aeae',
        'tertiary-fixed': '#e4e2e1',
        'on-tertiary-fixed': '#1b1c1c',
        'tertiary-fixed-dim': '#c8c6c5',
        'outline': '#aa8984',
        'outline-variant': '#5a403c',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        'inverse-primary': '#b52619',
        'surface-tint': '#ffb4a8',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'container-padding-mobile': '16px',
        'container-padding-desktop': '40px',
        'stack-sm': '8px',
        'unit': '4px',
        'stack-md': '16px',
        'gutter': '24px',
        'stack-lg': '32px',
      },
      fontFamily: {
        'display-lg': ['Chivo'],
        'display-lg-mobile': ['Chivo'],
        'body-md': ['Inter'],
        'headline-md': ['Chivo'],
        'label-caps': ['Inter'],
        'body-lg': ['Inter'],
      },
      fontSize: {
        'display-lg-mobile': ['32px', { lineHeight: '1.1', fontWeight: '900' }],
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.04em', fontWeight: '900' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '1.2', letterSpacing: '0.02em', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
